version: '3.4'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
  furny:
    image: ${DOCKER_REGISTRY-}furny
    build:
      context: .
      dockerfile: Dockerfile
